# Generated by Django 3.2.9 on 2021-11-04 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_views'),
        ('home', '0002_blogviews_postscore_userviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogviews',
            name='viewer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userviews',
            name='viewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='userviews',
            name='viewer',
            field=models.CharField(max_length=150),
        ),
    ]
